[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
web-sys = "0.3.60"
wasm-bindgen = "0.2.83"
log = "0.4.17"
wasm-logger = "0.2.0"
interpreter = { path = "../interpreter" }